### ISSUE TITLE
Rake aborted

### ISSUE THREAD

**Issue by chip** [imajes/postalmethods#3]
Hi,

Hey @imajes - Nice work on this gem.  I'm working on a project that will work with the postalmethods.com API and am just trying to get setup.  I've installed `rspec` and `soap4r`, but running rake causes this error:

```
/Users/chip/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/soap4r-1.5.8/lib/xsd/charset.rb:13: warning: variable $KCODE is no longer effective
/Users/chip/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:112:in `require': iconv will be deprecated in the future, u
se String#encode instead.
rake aborted!
XML processor module not found.
/Users/chip/code/causemetric/postalmethods/lib/postalmethods.rb:11:in `<class:Client>'
/Users/chip/code/causemetric/postalmethods/lib/postalmethods.rb:7:in `<module:PostalMethods>'
/Users/chip/code/causemetric/postalmethods/lib/postalmethods.rb:4:in `<top (required)>'
/Users/chip/code/causemetric/postalmethods/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)
```

It doesn't look like this repo has been committed to in several years, so I've forked it, but if you have any suggestions or feedback, it would be greatly appreciated.  Thanks again.

**Comment by imajes** [comment]
Yeah- it was a project for them to build an initial API client... i don't
even know if it still works :) - obviously it's not quite as up to date.

perhaps it's best to talk to them about fixing up a new version?

On Thu, Oct 23, 2014 at 5:03 PM, Chip Castle notifications@github.com
wrote:

> Hi,
> 
> Hey @imajes https://github.com/imajes - Nice work on this gem. I'm
> working on a project that will work with the postalmethods.com API and am
> just trying to get setup. I've installed rspec and soap4r, but running
> rake causes this error:
> 
> /Users/chip/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/soap4r-1.5.8/lib/xsd/charset.rb:13: warning: variable $KCODE is no longer effective
> /Users/chip/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:112:in `require': iconv will be deprecated in the future, u
> se String#encode instead.
> rake aborted!
> XML processor module not found.
> /Users/chip/code/causemetric/postalmethods/lib/postalmethods.rb:11:in`class:Client'
> /Users/chip/code/causemetric/postalmethods/lib/postalmethods.rb:7:in `<module:PostalMethods>'
> /Users/chip/code/causemetric/postalmethods/lib/postalmethods.rb:4:in`<top (required)>'
> /Users/chip/code/causemetric/postalmethods/Rakefile:2:in `<top (required)>'
> (See full trace by running task with --trace)
> 
> It doesn't look like this repo has been committed to in several years, so
> I've forked it, but if you have any suggestions or feedback, it would be
> greatly appreciated. Thanks again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/imajes/postalmethods/issues/3.

## 

James Cox,
Consultant, Raconteur, Photographer, Entrepreneur
t: +1 347 433 0567  e: james@imaj.es w: http://imaj.es/
talk: http://twitter.com/imajes photos: http://500px.com/imajes

**Comment by chip** [comment]
@imajes - Thanks for the prompt reply. :smile:   I'll contact them and also see what I can do on my end.
